[package]
name = "beacon"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19", features = ["dynamic_linking", "file_watcher"] }
bevy_ecs_ldtk = { git = "https://github.com/jgayfer/bevy_ecs_ldtk", branch="scenes", features = ["scene"] }
avian2d = "0.7"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
